<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();

    $_infoblock = Mage::getStoreConfig('porto_settings/contacts/infoblock', $code);
    $custom_block = Mage::getStoreConfig('porto_settings/contacts/customblock', $code);
?>
<div class="container">
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php if($custom_block): ?>
<div class="row">
    <div class="col-md-12">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml(); ?>
    </div>
</div>
<?php endif; ?>
<div class="row">
<div class="acl-nlt-cont-page-cp">
<div class="col-main">
<div id="messages_product_view"></div>
<div class="page-title">
<h1 style="color: #000;font-size: 38px;margin-bottom: 36px;font-weight: 300;">Contact Us</h1>
</div>
<div class="col-left01" style="line-height: 22px;">
<p style="padding-top: 16px;">Your outstanding shopping experience is our top priority. If we can help in any way, please let us know.</p>
<p>Our wig experts are available to help Monday - Friday, 8:00 a.m. - 6:30 p.m. CST</p>
<p>Click on the chat box to have a live chat with customer service. If you happen to reach us offline don’t worry simply submit you query and we'll send you a reply within 12 hours.</p>
<p style="line-height: 32px;"><strong>PHONE: </strong>(+86) 15806502038，(+86) 18854283372</p>
<p style="line-height: 32px;"><strong>WHATSAPP:</strong>(+86) 15806502038，(+86) 18854283372</p>
<p style="line-height: 32px;"><strong>EMAIL:</strong> service@addcolo.com forest@addcolo.com</p>
<p style="padding-top: 10px;">We look forward to receiving your questions or comments and will respond as quickly as possible.</p>
<p style="line-height: 40px;"><img src="https://addcololive-6rdrwfw.netdna-ssl.com/media/wysiwyg/P1.png" alt="" /></p>
</div>
<div class="form_mess">
    <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <!-- <h2 class="legend"><?php echo Mage::helper('contacts')->__('Leave') ?> <?php echo Mage::helper('contacts')->__('a') ?> <b><?php echo Mage::helper('contacts')->__('Message') ?></b></h2> -->
    <legend class="legend"><span>Write <b>Us</b></span></legend><br>
    <div class="row">
        <ul class="form-list col-md-6">
            <li style="color: #D9365A;font-weight: 200;font-size: 20px;margin-bottom: 15px;"> Write Us</li>
            <li>
                <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                <div class="input-box">
                    <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                </div>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                <div class="input-box">
                    <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box input-textarea">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3" placeholder="<?php echo Mage::helper('contacts')->__('Comment') ?>"></textarea>
                </div>
            </li>
        <!-- </ul> -->
        <!-- <ul class="form-list col-md-6">    -->
            <li>
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
            </li>
        </ul>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
</div>
<div class="clear"></div>
</div>
</div>
</div>
<!-- <div class="row">
    <div class="col-md-8">
    <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <h2 class="legend"><?php echo Mage::helper('contacts')->__('Leave') ?> <?php echo Mage::helper('contacts')->__('a') ?> <b><?php echo Mage::helper('contacts')->__('Message') ?></b></h2>
    <div class="row">
        <ul class="form-list col-md-6">
            <li>
                <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                <div class="input-box">
                    <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                </div>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                <div class="input-box">
                    <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
        </ul>
        <ul class="form-list col-md-6">
            <li>
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box input-textarea">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3" placeholder="<?php echo Mage::helper('contacts')->__('Comment') ?>"></textarea>
                </div>
            </li>
            <li>
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
            </li>
        </ul>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
    </div>
    <div class="col-md-4 contact-info">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact') ?> <b><?php echo Mage::helper('contacts')->__('Details') ?></b></h2>
        <?php
            echo $_infoblock;
        ?>
    </div>
</div> -->
</div>