<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<header class="page-header type11 ">
   <span data-action="toggle-nav" class="action nav-toggle"><span>Toggle Nav</span></span>
    <div class="acl-nlt-header-sec">
        <div class="acl-nlt-header-sec-top">
            <a href="<?php echo Mage::getUrl('customer/account/login'); ?>" class="acl-nlt-header-top-login">Log In &gt;<em class="porto-icon-user"></em></a>
            <div class="acl-nlt-logo-box">
                <strong class="logo">
                    <?php if ($this->getIsHomePage()):?>
                    <strong><?php echo $this->getLogoAlt(); ?></strong><a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>"     /></a>
                        <?php else:?>
                        <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>"><strong><?php echo $this->getLogoAlt(); ?></strong><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
                        <?php endif; ?>
                </strong>
            </div>
            <a href="<?php echo Mage::getUrl('customer/account/create'); ?>" class="acl-nlt-header-top-join">Join</a>
        </div>
        <div class="acl-nlt-header-sec-bot">
            <div class="acl-nlt-header-sec-nav">
                <nav class="navigation sw-megamenu " role="navigation">
                    <?php echo $this->getChildHtml('topMenu') ?>
                </nav>
            </div>






         <div class="acl-nlt-header-sec-nav-right">
            <ul>
                <li class="acl-nlt-header-sec-nav-search">  <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <div class="search_area" style="display:none;"><div class="block block-search">
                 <?php echo $this->getChildHtml('topSearch'); ?>
                    </div>
                    </div>
                    </div>
                </li>
                <li class="acl-nlt-header-sec-nav-cart">
                    <div data-block="minicart" class="minicart-wrapper">
                        <?php echo $this->getChildHtml('minicart'); ?>
                    </div>
                </li>
            </ul>
        </div>






            
        </div>
   </div>
</header>
<script type="text/javascript">
    jQuery(function($){
        $('.search-toggle-icon').click(function()
        {
            $('.search_area').toggleClass('show');
        });
              
        jQuery('.nl-footer-colmn-sec h3').click(function() 
        {
            jQuery(this).next('.nl-footer-link-list').toggle();
            jQuery(this).toggleClass('expanded');
        });
    });
</script>
